#!/usr/bin/env lua
local package1 = arg[2]:gsub('&', '')
if arg[1] == "install" or arg[1] == "-S" then
	if arg[2] == "a" then
		local package2 = arg[3]:gsub('&', ''):gsub(' ', ''):gsub('.', '')
		os.execute("git clone https://aur.archlinux.org/"..package2..".git /tmp/lightpkg/"..package2)
		os.execute("cd /tmp/lightpkg/"..package2.." && makepkg -si")
		os.execute("rm -rf /tmp/lightpkg/*")
	else	
		os.execute("sudo pacman -S "..package1)
	end
end
if arg[1] == "update" or arg[1] == "-Syu" then
	print("AUR packages require you to reinstall them to update them!")
	os.execute("sudo pacman -Syu")
end
if arg[1] == "remove" or arg[1] == "-R" then
	os.execute("sudo pacman -R "..arg[2])
end
if #arg == 0 then
   print('Use "lightpkg install a PACKAGENAME" to install aur packages, and "lightpkg install PACKAGENAME for normal packages"')
end
